kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.20.0
    extraPortMappings:
      - containerPort: 30080 # ingress-nginx
        hostPort: 80
      - containerPort: 30443 # ingress-nginx
        hostPort: 443
